/*
 * This source file was generated by the Gradle 'init' task
 */
package jp.ac.metro_cit.adv_prog_2024.gomoku;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
