/*
 * This source file was generated by the Gradle 'init' task
 */
package jp.ac.metro_cit.adv_prog_2024.gomoku;

import jp.ac.metro_cit.adv_prog_2024.gomoku.ui.Ui;

public class App {
  public static void main(String[] args) {
    System.out.println(BuildConfig.ENV);
    Ui.openWindow();
  }
}
