/*
 * This source file was generated by the Gradle 'init' task
 */
package jp.ac.metro_cit.adv_prog_2024.gomoku;

import jp.ac.metro_cit.adv_prog_2024.gomoku.controller.GameCommunicationController;
import jp.ac.metro_cit.adv_prog_2024.gomoku.ui.Ui;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    GameCommunicationController gameCommunicationController =
        new GameCommunicationController(null, null, null, null);
    Ui.openStartWindow(gameCommunicationController);
    System.out.println(new App().getGreeting());
  }
}
