name: spotbugs

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "corretto"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: spotbugs
      shell: bash
      run: ./gradlew spotbugsMain spotbugsTest
      continue-on-error: true

    - name: Set up reviewdog
      uses: reviewdog/action-setup@v1

    - name: Run reviewdog (pr)
      if: github.event_name == 'pull_request_target'
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        cat ./app/build/reports/spotbugs/main.sarif | reviewdog -f sarif -reporter=github-pr-review -name run-reviewdog -tee
        cat ./app/build/reports/spotbugs/test.sarif | reviewdog -f sarif -reporter=github-pr-review -name run-reviewdog -tee

    - name: Run reviewdog (push)
      if: github.event_name == 'push'
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        cat ./app/build/reports/spotbugs/main.sarif | reviewdog -f sarif -reporter=github-check -name run-reviewdog -tee
        cat ./app/build/reports/spotbugs/test.sarif | reviewdog -f sarif -reporter=github-check -name run-reviewdog -tee
