/*
 * This source file was generated by the Gradle 'init' task
 */
package jp.ac.metro_cit.adv_prog_2024.gomoku;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

public class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
