on:
  pull_request_target:
    branches: 
      - main
      - release/*
    types: 
      - opened
      - synchronize
      - reopened 
  push:
    branches-ignore:
      - main
      - release/*

jobs:
  spotless:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request_target'
        id: pr
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.payload.pull_request.number,
            });
            return pullRequest
            
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          ref: ${{fromJSON(steps.pr.outputs.result).merge_commit_sha}}

      - uses: actions/checkout@v4
        if: github.event_name == 'push'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: check
        if: github.event_name == 'push'
        run: ./gradlew check

      - name: Suggest changes
        uses: reviewdog/action-suggester@v1
        if: github.event_name == 'pull_request_target'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: spotless
          fail_on_error: true

  spotbugs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request_target'
        id: pr
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.payload.pull_request.number,
            });
            return pullRequest
            
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          ref: ${{fromJSON(steps.pr.outputs.result).merge_commit_sha}}

      - uses: actions/checkout@v4
        if: github.event_name == 'push'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Spotbugs
        run: ./gradlew spotbugsMain spotbugsTest
        continue-on-error: true

      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat ./app/build/reports/spotbugs/main.sarif | reviewdog -f sarif -reporter=github-pr-check -name run-reviewdog -tee
          cat ./app/build/reports/spotbugs/test.sarif | reviewdog -f sarif -reporter=github-pr-check -name run-reviewdog -tee
