on:
  pull_request_target:
    branches:
      - main
      - release/*
    types: 
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test
        run: ./gradlew jacocoTestReport

      - name: Report test results
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: "**/build/test-results/test/TEST-*.xml"

      - name: Jacoco Report
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/**/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 85
          min-coverage-changed-files: 90
