on:
  pull_request_target:
    branches:
      - main
      - release/*
    types: 
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        id: pr
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.payload.pull_request.number,
            });
            return pullRequest
            
      - uses: actions/checkout@v4
        with:
          ref: ${{fromJSON(steps.pr.outputs.result).merge_commit_sha}}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test
        run: ./gradlew jacocoTestReport --no-parallel
        continue-on-error: true

      - name: Report test results
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: "**/build/test-results/test/TEST-*.xml"

      - name: Jacoco Report
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/**/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 85
          min-coverage-changed-files: 90
